name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ffmpeg aplay cmake make build-essential \
            libavcodec-dev libavdevice-dev libavfilter-dev \
            libavformat-dev libavutil-dev libswresample-dev \
            libswscale-dev libncurses5-dev

      - name: Configure project
        run: cmake -DCMAKE_BUILD_TYPE=Release .

      - name: Build project
        run: cmake --build . --config Release

      - name: Package binary as tarball
        run: |
          mkdir -p release
          cp asciivideo release/
          tar -czvf asciivideo-linux.tar.gz -C release asciivideo

      - name: Install fpm (Deb package builder)
        run: |
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Package binary as .deb
        run: |
          # Extract version from tag (GITHUB_REF is "refs/tags/v1.0.0")
          VERSION=${GITHUB_REF#refs/tags/v}
          fpm -s dir -t deb -n asciivideo -v $VERSION --prefix /usr/local/bin asciivideo

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            asciivideo-linux.tar.gz
            asciivideo.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
